import csv
from pathlib import Path

from doost import db
from doost.address import Address, format_birthday, parse_birthday
from doost.plugins.io import ProgressCallback, report_progress
from doost.plugins.registry import register


class CSVPlugin:
    """Import/export addresses in CSV format.

    The CSV format uses the following header:

        name,email,birthday,address,phone,mobile,custom,notes

    Each row represents one address entry. The `id` field is intentionally
    omitted because it is generated by the database.
    """

    format = "csv"

    def import_data(self, path: Path, session_factory, progress_callback: ProgressCallback | None = None) -> None:
        """Import addresses from a CSV file.

        Args:
            path: Path to the CSV input file.
            session_factory: Callable returning a DB session.

        Notes:
            - Invalid rows are skipped silently.
            - Duplicate addresses are ignored.
        """
        with path.open(newline="", encoding="utf-8") as fh:
            reader = list(csv.DictReader(fh))

        total = len(reader)
        report_progress(progress_callback, 0, total)

        with session_factory() as session:
            for index, row in enumerate(reader, start=1):
                try:
                    address = Address(
                        id=None,
                        name=row["name"].strip(),
                        email=row["email"].strip(),
                        birthday=parse_birthday(row.get("birthday", "")),
                        address=row.get("address", "").strip(),
                        phone=row.get("phone", "").strip(),
                        mobile=row.get("mobile", "").strip(),
                        custom=row.get("custom", "").strip(),
                        notes=row.get("notes", "").strip(),
                    )
                    if not address.name or not address.email:
                        continue
                    db.insert_address(session, address)
                except KeyError, ValueError:
                    # Missing fields or duplicate entry
                    continue
                finally:
                    report_progress(progress_callback, index, total)

    def export_data(
        self,
        path: Path,
        addresses: list[Address],
        progress_callback: ProgressCallback | None = None,
    ) -> None:
        """Export addresses to a CSV file.

        Args:
            path: Destination file path.
            addresses: List of addresses to export.

        Notes:
            - Existing files are overwritten.
            - UTF-8 encoding is always used.
        """
        total = len(addresses)
        report_progress(progress_callback, 0, total)

        with path.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(
                fh,
                fieldnames=["name", "email", "birthday", "address", "phone", "mobile", "custom", "notes"],
            )
            writer.writeheader()

            for index, address in enumerate(addresses, start=1):
                writer.writerow(
                    {
                        "name": address.name,
                        "email": address.email,
                        "birthday": format_birthday(address.birthday),
                        "address": address.address,
                        "phone": address.phone,
                        "mobile": address.mobile,
                        "custom": address.custom,
                        "notes": address.notes,
                    }
                )
                report_progress(progress_callback, index, total)


# Register plugin on import
register(CSVPlugin())
